### ISSUE TITLE
hmm what if users array is empty assuming you did not have the fakeData file?

### ISSUE THREAD

**Issue by ninjamovesonly** [Franklin-raph/redux-learn-one#1]
https://github.com/Franklin-raph/redux-learn-one/blob/32f52ae8236e04d502dbe8ed2f7c24a6218368ec/src/pages/Home.jsx#L22

**Comment by Franklin-raph** [comment]
Yeah I would return a message to the users saying e.g "No users data
available" i.e when the length of the users data array is zero
